apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video-streaming

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-deployment.yaml
  - auth-service-deployment.yaml
  - file-service-deployment.yaml
  - upload-service-deployment.yaml
  - streaming-service-deployment.yaml
  - upload-app-deployment.yaml
  - streaming-app-deployment.yaml
  - ingress.yaml
  - hpa.yaml